---
- name: install a simple webserver on an ubuntu and copy 1 html file based on jinja j2 template
  hosts: localhost
  vars_files:
    - vars/families.yaml
    - vars/webserver.yaml
  vars:
    package_name: apache2
    package_state: present
    webserver_root: /var/www/html
    webserver_index: index.html
    webserver_template: index.html.j2
    http_host: "your_domain"
    http_conf: "your_domain.conf"
    http_port: "80"
    disable_default: true    

  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copy index test page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Set up Apache virtuahHost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    # start and configure apache2
    - name: start the apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
        
